stages:
  - test
  - build
  - publish

.golang_template:
  image: golang:latest
  before_script:
    - make go/downloadDependencies

format:
  extends: .golang_template
  stage: test
  script:
    - make go/format

test:
  extends: .golang_template
  stage: test
  script:
    - make go/test

build_pages:
  stage: build
  image: registry.gitlab.com/pages/hugo/hugo:latest
  script:
    - apk add make
    - make docs/downloadTheme
    - make docs/build
  artifacts:
    paths:
      - docs/public/

pages:
  stage: publish
  image: alpine
  only:
    - main
  script:
    - mv docs/public/ public/
  artifacts:
    paths:
      - public/

.build_template:
  extends: .golang_template
  stage: build
  cache:
    key: build-cache
    paths:
      - dist/
  artifacts:
    paths:
      - dist/*.tar.gz
      - dist/checksums.txt
    expire_in: 1 day

build_snapshot:
  extends: .build_template
  only:
    - main
    - triggers
    - schedules
  script:
    - git fetch --tags
    - make build/snapshot

build_release:
  extends: .build_template
  only:
    - tags
  script:
    - git fetch --tags
    - make build/release

docker_push_gitlab:
  stage: publish
  only:
    - main
    - tags
  image: docker:stable
  services:
    - docker:dind
  cache:
    key: build-cache
    paths:
      - dist/
  before_script:
    - apk add git
    - apk add make
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - make build/docker
    - docker tag registry.gitlab.com/hectorjsmith/grafana-matrix-forwarder registry.gitlab.com/hectorjsmith/grafana-matrix-forwarder:$(git describe --tags)
    - docker push registry.gitlab.com/hectorjsmith/grafana-matrix-forwarder
