stages:
  - test
  - build
  - publish

.go-template:
  image: golang:latest
  before_script:
    - make install-deps

build-pages:
  stage: build
  image: registry.gitlab.com/pages/hugo/hugo:latest
  script:
    - apk add make
    - make docs/download-theme
    - make docs/build
  artifacts:
    paths:
      - docs/public/

pages:
  stage: publish
  image: alpine
  only:
    - main
  script:
    - mv docs/public/ public/
  artifacts:
    paths:
      - public/

format:
  extends: .go-template
  stage: test
  script:
    - make format

dependencies:
  extends: .go-template
  stage: test
  script:
    - make go-mod-tidy

test:
  extends: .go-template
  stage: test
  script:
    - make test

.build-job-template:
  extends: .go-template
  stage: build
  cache:
    key: build-cache
    paths:
      - dist/
  artifacts:
    paths:
      - dist/*.tar.gz
      - dist/checksums.txt
    expire_in: 1 day

build-snapshot:
  extends: .build-job-template
  only:
    - main
    - triggers
    - schedules
  script:
    - git fetch --tags
    - make build/snapshot

build-release:
  extends: .build-job-template
  only:
    - tags
  script:
    - git fetch --tags
    - make build/release

docker-push-gitlab:
  stage: publish
  only:
    - main
    - tags
  image: docker:stable
  services:
    - docker:dind
  cache:
    key: build-cache
    paths:
      - dist/
  before_script:
    - apk add git
    - apk add make
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - make build/docker
    - docker tag registry.gitlab.com/hectorjsmith/grafana-matrix-forwarder registry.gitlab.com/hectorjsmith/grafana-matrix-forwarder:$(git describe --tags)
    - docker push registry.gitlab.com/hectorjsmith/grafana-matrix-forwarder
